# Generated by Django 4.1.3 on 2023-01-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reporter', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
